### ISSUE TITLE
which browser in the screenshot?

### ISSUE THREAD

**Issue by gour** [org-roam/org-roam-server#140]
Hello,

exploring different options for note-taking (Zettelkasten method) and Emacs/org-roam looks as the most complete one, open-source etc...Now I wonder which browser app is used on the screenshot?

When I try to visit `http://localhost:8080/` I always get firefox launched (it's default browser), so wonder how to get graph visible **within** Emacs?

**Comment by goktug97** [comment]
It is Qutebrowser. It looks like it is running inside of Emacs because the colors are exactly the same (because I used the same color for org-roam-server as my emacs configuration.) but actually they are different windows. You can use https://github.com/manateelazycat/emacs-application-framework to run any browser inside of your emacs.

**Comment by gour** [comment]
> It is Qutebrowser. It looks like it is running inside of Emacs because the colors are exactly the same (because I used the same color for org-roam-server as my emacs configuration.) but actually they are different windows. 

Heh, well done...masquerading.

> You can use https://github.com/manateelazycat/emacs-application-framework to run any browser inside of your emacs.

Thanks. Will investigate further... ;)
