### ISSUE TITLE
Add a setting to select dark mode by default

### ISSUE THREAD

**Issue by michaelmrose** [org-roam/org-roam-server#21]
org-roam-server-colormode or some such to avoid clicking dark mode at the beginning of each session. Given a dark emacs theme and viewing the server on an EAF browser window 

https://github.com/manateelazycat/emacs-application-framework

the background is dark as is the text but otherwise works great.

**Comment by goktug97** [comment]
The colormode setting is now saved in the browser's localStorage. It will load to darkmode if you've chosen it previously.

> Given a dark emacs theme and viewing the server on an EAF browser window
manateelazycat/emacs-application-framework
the background is dark as is the text but otherwise works great.

is this a separate problem? I tried in EAF with dark-mode (doom-molokai) and everything works perfectly.
