### ISSUE TITLE
Feature Request on Filter with ROAM_TAGS

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-server#24]
The tag of org roam dont show up in title, so we could not find out files by tag in org roam server right now.

Aside, filters on tag system can do quite a lot as we could make up our own structure by tags.

**Comment by hyan46** [comment]
I have a similar question, my current setup already have hundreds of nodes and the graph can quickly become too distracted. For example, it includes nodes such as Work and family related documents. If I am working, I can simplify filter out family related nodes to focus. 
 
On the other hand, buffer mode showing too less information and only showing the neighborhood. I think combining `ROAM_TAGS` is probably one way to solve this problem, so we can show the sub-graph instead of the full graph to be more focused on particular task.

**Comment by ertwro** [comment]
I think this is gonna quickly get out of hand. Implementing a new filtering scheme for every org-roam new feature can become overwhelming fast. Exposing variables and letting local modifications be done by individual users is a far more sustainable approach.

**Comment by hyan46** [comment]
@ertwro I see your points. I agree that `ROAM_TAG` is a new feature in `org-roam` and it may not be the best way to develop the filtering system. However, I still felt filtering system would be a useful features to implement since this could make “Database Network” more useful when visualizing very large graph and to make people more focused.  The current best option that I can think of is by `ROAM_TAG`, which currently have little use in the `org-roam-server`. May be there are other ways of implementing this.

**Comment by jasondunsmore** [comment]
Filtering the graph based on ROAM_TAGS makes sense to me. I imagine ROAM_TAGS as a cleaner way to implement tagging than with "- tags :: ". Currently, you can filter a graph based on a "- tags :: " tag by clicking on the "Buffer Network" view and clicking on the tag name.

**Comment by qlibp** [comment]
> Filtering the graph based on ROAM_TAGS makes sense to me. I imagine ROAM_TAGS as a cleaner way to implement tagging than with "- tags :: ". Currently, you can filter a graph based on a "- tags :: " tag by clicking on the "Buffer Network" view and clicking on the tag name. 

i see, this could be a work around

**Comment by hyan46** [comment]
> Filtering the graph based on ROAM_TAGS makes sense to me. I imagine ROAM_TAGS as a cleaner way to implement tagging than with "- tags :: ". Currently, you can filter a graph based on a "- tags :: " tag by clicking on the "Buffer Network" view and clicking on the tag name.

Yes, this could be a work around but needs to generate unnecessary nodes and limit the use when editing since "Buffer Network" will change based on what file you are editing right now. I think using `ROAM_TAGS` could be a better way so we don't need to define Node like "Active", "Finished" for project pages when using `org-roam` for project management, which should be a status tag rather than a node in the graph. 

Also, filtering based on `ROAM_TAGS` can also enable filtering with multiple logic conditions. Again, not sure how easy it is to enable a filtering system with multiple logic conditions but a simple binary filter would work for now. I think filtering with multiple logic conditions could be related to #23, but on a different way of filtering based on TAGS rather than node.

**Comment by goktug97** [comment]
https://github.com/org-roam/org-roam-server/commit/84bda2276e0de6ed90ef6adcae25877174521435
You can filter the database network using ROAM_TAGS now.

**Comment by hyan46** [comment]
Thank you @goktug97! One thing I am wondering, currently the version keep all the nodes when do select one or multiple filters, however, on my installed version, all the links are gone (not sure if it is my problem or this has not been implemented), which is important to show the relationship between them. It would be good to show the selected nodes with the links between them (e.g., like a sub-graph of the entire graph)

**Comment by naistran** [comment]
84bda22 breaks `org-roam-server` for me. I now get this error for http://127.0.0.1:8080/roam-data?force=1&token=null:

```
500 Internal Error
Internal error when handling this request.

error: (emacsql-error near line 25: near "LEFT": syntax error)
```

No nodes are displayed.

b06828e works perfectly.

**Comment by goktug97** [comment]
@naistran It seems the update didn't work for some people. #28 Hopefully it is fixed now.
