### ISSUE TITLE
[Feature Request] Differentiate Notes from Tags by color-coding based on number of lines?

### ISSUE THREAD

**Issue by oblitzitate** [org-roam/org-roam-server#58]
My tag files tend to have the same number of lines since it's mainly just template + linking other files through `- tags ::`. You can use the number of lines to differentiate notes from tags. 

I was thinking tags should be grayish, whereas notes should be more saturated. Maybe even extend it further by making the color saturation a spectrum so you can differentiate between small notes and large notes.

**Comment by goktug97** [comment]
The `org-roam-server-visjs-json` function is already crowded and is causing performance issues for some people with a lot of notes. I added `org-roam-server-network-poll` variable so that automatic update can be disabled to increase the performance. To do what you want, every file must be opened and inspected which will cause more performance issues. But there has been a pull request https://github.com/org-roam/org-roam-server/pull/71  which is merged to the master and with this new feature you can customize node options. I changed the JS part so if the options are set by the user they won't be touched. 

For example (not tested) below code sets the size of the node depending on the number of lines;
```elisp
(defun set-size (node)
  (with-temp-buffer
    (insert-file-contents (xml-escape-string (car node)))
    (let ((n-lines (count-lines (point-min) (point-max))))
      (list (cons 'value n-lines)))))

(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-extra-node-options 'set-size))
```
