### ISSUE TITLE
No application associated with org-protocol:protocol

### ISSUE THREAD

**Issue by KonVas** [org-roam/org-roam-server#70]
I have uploaded to latest version but it stopped opening my files, giving the message in the subject. The app is running and I haven't changed anything in my configuration of this app.

**Comment by goktug97** [comment]
While you said you haven't changed anything, this has something to do with your setup. I've just updated to the latest version of `org-roam` and everything works perfectly. This issue is not directly related to `org-roam-server` but `org-roam`. You can try running `org-roam-graph` function and test `org-protocol` in there. If it doesn't work either you should open this issue in https://github.com/org-roam/org-roam
