### ISSUE TITLE
Allow Server Access from other devices

### ISSUE THREAD

**Issue by RyanGreenup** [org-roam/org-roam-server#9]
I would love to be able to point my ipad to my computer and access the server, unfourtunately I can only access it at `localhost:8080` but not at `192.xxx.x.xxx:8080`.

**Comment by goktug97** [comment]
Can you set ‘httpd-host’

‘’’elisp
(require simple-httpd)
(setq httpd-host “0.0.0.0”)
‘’’

I think this can be added as a customizable in the future

**Comment by goktug97** [comment]
Can you set `httpd-host`

```elisp
(require 'simple-httpd)
(setq httpd-host “0.0.0.0”)
```

**Comment by RyanGreenup** [comment]
Ahh perfect thanks. This works really well! 

I've noticed also that it seems to work better on *Firefox* than *Safari* in *iOS* and the warning is far less obtrusive.

Now I just have to figure out how to implement basic `http` authentication.

**Comment by goktug97** [comment]
Added new customizable variables.
`org-roam-server-host`, `org-roam-server-port`, `org-roam-server-authenticate`
You can set `org-roam-server-host` to "0.0.0.0" to access from other devices.
If you want authentication, you can set `org-roam-server-authenticate` to `t` then you have to provide the token while opening the webpage. When you set `org-roam-server-authenticate` to `t` it will give you the token while starting the server. Then you can send the token to your iPad to login easily because the token is rather long with 64 characters.
